Q1

In [ ]:
#1
import numpy as np
A = np.array([ [12, 5, 8, 20], [ 7, 15, 3, 11], [25, 9, 18, 6], [10, 14, 2, 16] ])  
print(np.mean(A,axis=1))

[11.25  9.   14.5  10.5 ]


In [ ]:
#2,3,4
A=np.where(A>np.mean(A,axis=1),1,0)
print(A)

[[1 0 0 1]
 [0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]]


#5
every row contains equal no. of elements above the average


Q2

In [4]:
X = np.array([ [10, 100, 5], [12, 110, 6], [11, 105, 7], [13, 500, 6], [14, 108, 8], [15, 115, 9] ]) 
print(np.mean(X,axis=0))
print(np.std(X,axis=0))

[ 12.5        173.           6.83333333]
[  1.70782513 146.31017281   1.34370962]


In [5]:
condition=np.abs(X-np.mean(X,axis=0))>2*np.std(X,axis=0)
print(X[condition])

[500]
